return {
  ["1"] = {
    id = "1",
    name = "普通捐献",
    vip = 0,
    price = {4,1,10000},
    progress = 1,
    player_integral = 100,
    exp = 10,
    crit_chance = 2000,
    crit_multiplier = 15000,
    display_string_normal = "成员%s普通捐献，为军团增加%s点经验",
    display_string_crit = "成员%s普通捐献，触发了暴击，为军团增加%s点经验",
  },
  ["2"] = {
    id = "2",
    name = "中级捐献",
    vip = 0,
    price = {4,2,30},
    progress = 3,
    player_integral = 500,
    exp = 50,
    crit_chance = 1000,
    crit_multiplier = 20000,
    display_string_normal = "成员%s中级捐献，为军团增加%s点经验",
    display_string_crit = "成员%s中级捐献，触发了暴击，为军团增加%s点经验",
  },
  ["3"] = {
    id = "3",
    name = "高级捐献",
    vip = 1,
    price = {4,2,300},
    progress = 5,
    player_integral = 3000,
    exp = 300,
    crit_chance = 500,
    crit_multiplier = 25000,
    display_string_normal = "成员%s高级捐献，为军团增加%s点经验",
    display_string_crit = "成员%s高级捐献，触发了暴击，为军团增加%s点经验",
  },

}