return {
  ["1"] = {
    log_id = "1",
    log_event = "创建帮派",
    arg_order = "roleid|gangname",
    log_str = "%s创建了帮派%s。",
    log_example = "懒懒的布鲁斯创建了帮派蠢萌门。",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["2"] = {
    log_id = "2",
    log_event = "帮派升级",
    arg_order = "gangname|ganglevel",
    log_str = "%s升级为%s级帮派。",
    log_example = "蠢萌门升级为2级帮派。",
    mail_id = 2003,
    arg_mail = "ganglevel",
    mail_player = 2,
  },
  ["3"] = {
    log_id = "3",
    log_event = "帮派改名",
    arg_order = "gangname",
    log_str = "帮派名称被修改为%s。",
    log_example = "帮派名称被修改为蠢萌门。",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["4"] = {
    log_id = "4",
    log_event = "加入帮派",
    arg_order = "roleid",
    log_str = "%s加入了帮派！热烈欢迎！",
    log_example = "呆呆的奥维斯加入了帮派！热烈欢迎！",
    mail_id = 2001,
    arg_mail = "gangname",
    mail_player = 1,
  },
  ["5"] = {
    log_id = "5",
    log_event = "退出帮派",
    arg_order = "roleid",
    log_str = "很遗憾，%s离开了帮派。",
    log_example = "很遗憾，傻傻的罗伯斯离开了帮派。",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["6"] = {
    log_id = "6",
    log_event = "职位调整",
    arg_order = "roleid|posid",
    log_str = "%s的职位被调整为%s。",
    log_example = "萌萌的艾瑞斯的职位被调整为副会长。",
    mail_id = 2004,
    arg_mail = "posid",
    mail_player = 1,
  },
  ["7"] = {
    log_id = "7",
    log_event = "踢出玩家",
    arg_order = "roleid",
    log_str = "%s被逐出了帮派。",
    log_example = "美美的爱丽丝被逐出了帮派。",
    mail_id = 2002,
    arg_mail = "gangname",
    mail_player = 1,
  },
  ["8"] = {
    log_id = "8",
    log_event = "击杀BOSS",
    arg_order = "roleid|senceid",
    log_str = "%s最终击杀了%s的训练师！",
    log_example = "萌萌的艾瑞斯最终击杀了西海龙宫的训练师！",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["9"] = {
    log_id = "9",
    log_event = "帮派转让",
    arg_order = "gangname|roleid",
    log_str = "%s被转让给%s。",
    log_example = "蠢萌门被转让给呆呆的奥维斯。",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["50"] = {
    log_id = "50",
    log_event = "帮派贡献",
    arg_order = "roleid|gxid",
    log_str = "%s签到了%s。",
    log_example = "呆呆的奥维斯签到了金币贡献。",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },
  ["100"] = {
    log_id = "100",
    log_event = "申请入帮",
    arg_order = "roleid",
    log_str = "[]",
    log_example = "[]",
    mail_id = 0,
    arg_mail = "[]",
    mail_player = 0,
  },

}