return {
  ["1"] = {
    post_id = 1,
    post = "帮主",
    max_number = 1,
    rm_bz = 1,
    rm_fbz = 1,
    rm_zy = 1,
    tc_fbz = 1,
    tc_zy = 1,
    tc_cy = 1,
    xiugai_boss = 1,
    xiugai_mingzi = 1,
    xiugai_xuanyan  = 1,
    xiugai_yaoqiu = 1,
    chuli = 1,
    xianshi = "转让帮主,修改帮派名称,职务任命,设置申请条件,帮派收人,帮派踢人,修改帮派宣言,选择帮派训练营,参战训练营,帮派聊天,帮派贡献",
  },
  ["2"] = {
    post_id = 2,
    post = "副帮主",
    max_number = 2,
    rm_bz = 0,
    rm_fbz = 0,
    rm_zy = 1,
    tc_fbz = 0,
    tc_zy = 1,
    tc_cy = 1,
    xiugai_boss = 1,
    xiugai_mingzi = 0,
    xiugai_xuanyan  = 1,
    xiugai_yaoqiu = 1,
    chuli = 1,
    xianshi = "职务任命,设置申请条件,帮派收人,帮派踢人,修改帮派宣言,选择帮派训练营,参战训练营,帮派聊天,帮派贡献",
  },
  ["3"] = {
    post_id = 3,
    post = "精英",
    max_number = 10,
    rm_bz = 0,
    rm_fbz = 0,
    rm_zy = 0,
    tc_fbz = 0,
    tc_zy = 0,
    tc_cy = 0,
    xiugai_boss = 0,
    xiugai_mingzi = 0,
    xiugai_xuanyan  = 0,
    xiugai_yaoqiu = 0,
    chuli = 0,
    xianshi = "参战训练营,帮派聊天,帮派贡献",
  },
  ["4"] = {
    post_id = 4,
    post = "帮众",
    max_number = 0,
    rm_bz = 0,
    rm_fbz = 0,
    rm_zy = 0,
    tc_fbz = 0,
    tc_zy = 0,
    tc_cy = 0,
    xiugai_boss = 0,
    xiugai_mingzi = 0,
    xiugai_xuanyan  = 0,
    xiugai_yaoqiu = 0,
    chuli = 0,
    xianshi = "参战训练营,帮派聊天,帮派贡献",
  },

}